### ISSUE TITLE
`compare` fails...

### ISSUE THREAD

**Issue by ghost** [sven15/dapscompare#13]
So, after successfully creating reference images, `compare` now fails:

```
Traceback (most recent call last):
  File "/usr/bin/dapscompare", line 57, in run
    runTests(testcase)
  File "/usr/bin/dapscompare", line 106, in runTests
    imgComp = imread(comparisonPath+filename)
  File "/usr/lib64/python3.4/site-packages/scipy/misc/pilutil.py", line 154, in imread
    im = Image.open(name)
  File "/usr/lib64/python3.4/site-packages/PIL/Image.py", line 2282, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '[repo]/suse-xsl/tests/dapscompare-tests/db4-image/dapscompare-comparison/4e939befc302936bf577dacecbedd2da/cha.image.html.0.png'
```

**Comment by svenseeberg** [comment]
yeah, changing number of resulting images wasn't really handled yet.
