### ISSUE TITLE
single-quoted html-width value throws off dapscompare in various ways

### ISSUE THREAD

**Issue by ghost** [sven15/dapscompare#15]
@b648bbd0, I get this traceback:

```
Traceback (most recent call last):
  File "/usr/bin/dapscompare", line 365, in <module>
    main()
  File "/usr/bin/dapscompare", line 348, in main
    cfg = MyConfig()
  File "/usr/bin/dapscompare", line 149, in __init__
    self.loadConfig()
  File "/usr/bin/dapscompare", line 223, in loadConfig
    if int(content[hashsum]['Width']) not in self.htmlWidth:
ValueError: invalid literal for int() with base 10: "'600"
```

Additionally, --load-config should be the default: it does not make sense to compare something using completely different parameters. I don't even think there is much of a use case for an option disabling loading the configuration file.

**Comment by svenseeberg** [comment]
seems to be a problem with the command line options ... the single quote in "'600" should not be there. can you find the parameters in your history? i could also implement some input validation.

**Comment by ghost** [comment]
Aaaah!! I got it. I used the following as the parameter `--html-width='600,1280,1920'` And I did not use that directly, but from a "config" file (via `cat`). So, that seems to be the issue...
