### ISSUE TITLE
List index out of range error in GUI

### ISSUE THREAD

**Issue by ghost** [sven15/dapscompare#22]
After running a comparison run and then closing the window...

```
Starting Qt GUI
Traceback (most recent call last):
  File "/usr/bin/dapscompare", line 415, in <module>
    main()
  File "/usr/bin/dapscompare", line 406, in main
    spawnGui()
  File "/usr/bin/dapscompare", line 376, in spawnGui
    ex = qtImageCompare(cfg,dataCollection)
  File "/usr/share/dapscompare/modules/qtcompare.py", line 49, in __init__
    self.initUI(cfg,dta)
  File "/usr/share/dapscompare/modules/qtcompare.py", line 90, in initUI
    self.loadImage(imagesList[self.imagePos])
IndexError: list index out of range
```

(This was on the 0.2.0 version, not current develop. Also not sure exactly whether I can easily reproduce it.)

**Comment by svenseeberg** [comment]
probably fixed?!
